name: Run Selenium Test Final Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  saucedemo-test-selenium:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
      
    - name: Setup gradlew
      run: chmod +x gradlew 
      
    - name: Execute Test Cucumber
      run: ./gradlew cucumber

    - name: Execute Test API
      run: ./gradlew api

    - name: Execute Test WEB
      run: ./gradlew web

    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.3
      if: always()
      with:
        name: Cucumber Report
        path: reports
        
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        PERSONAL_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        PUBLISH_DIR: reports
